"""Add proxy_id to accounts

Revision ID: 0edc409e37c2
Revises: 2e5caf2e080e
Create Date: 2025-12-09 14:36:06.231708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0edc409e37c2'
down_revision = '2e5caf2e080e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('proxy_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'proxies', ['proxy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'proxy_id')
    # ### end Alembic commands ###

