"""Initial migration with all tables

Revision ID: 2e5caf2e080e
Revises: 
Create Date: 2025-12-09 14:15:23.111960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5caf2e080e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('accounts_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_paths', sa.JSON(), nullable=False),
    sa.Column('media_type', sa.Enum('PHOTO', 'VIDEO', 'CAROUSEL', 'REEL', name='mediatype'), nullable=False),
    sa.Column('caption_original', sa.Text(), nullable=False),
    sa.Column('original_language', sa.String(length=10), nullable=False),
    sa.Column('target_groups', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'POSTING', 'COMPLETED', 'FAILED', name='poststatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proxies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('HTTP', 'SOCKS5', name='proxytype'), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'FAILED', 'CHECKING', name='proxystatus'), nullable=False),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('assigned_accounts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translations_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text_original', sa.Text(), nullable=False),
    sa.Column('language_from', sa.String(length=10), nullable=False),
    sa.Column('language_to', sa.String(length=10), nullable=False),
    sa.Column('text_translated', sa.Text(), nullable=False),
    sa.Column('service', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_cache_language_from'), 'translations_cache', ['language_from'], unique=False)
    op.create_index(op.f('ix_translations_cache_language_to'), 'translations_cache', ['language_to'], unique=False)
    op.create_index(op.f('ix_translations_cache_text_original'), 'translations_cache', ['text_original'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'EDITOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('session_data', sa.JSON(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('proxy_url', sa.String(length=500), nullable=True),
    sa.Column('proxy_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'BANNED', 'COOLDOWN', 'LOGIN_REQUIRED', 'PROXY_ERROR', name='accountstatus'), nullable=False),
    sa.Column('last_post_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('posts_count_today', sa.Integer(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('posts_limit_per_day', sa.Integer(), nullable=True),
    sa.Column('warmup_stage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='logstatus'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_table('post_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('caption_translated', sa.Text(), nullable=False),
    sa.Column('instagram_media_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'POSTING', 'SUCCESS', 'FAILED', name='postexecutionstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_executions')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_translations_cache_text_original'), table_name='translations_cache')
    op.drop_index(op.f('ix_translations_cache_language_to'), table_name='translations_cache')
    op.drop_index(op.f('ix_translations_cache_language_from'), table_name='translations_cache')
    op.drop_table('translations_cache')
    op.drop_table('proxies')
    op.drop_table('posts')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###

