"""add_email_to_accounts

Revision ID: 9012a7537f3f
Revises: 0edc409e37c2
Create Date: 2025-12-21 20:26:32.749749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9012a7537f3f'
down_revision = '0edc409e37c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'email')
    # ### end Alembic commands ###

